### PR TITLE
Just everything changed

### PR DESCRIPTION
**Pull request by xKRISTOFx**

### CODE REVIEW

**Comment by xKRISTOFx** [comment]
@rvaidun merged main changes from other PR here to simplify workflow, check yourself if everything is right. Btw in my repo there is PR with preview deployment

**Comment by ronaldrupp** [comment]
Thanks for including my PRs @xKRISTOFx. Preview looks pretty good.

**Comment by rvaidun** [comment]
image
Upload and upload reaction are not aligned

**Comment by ronaldrupp** [comment]
> image
> 
> Upload realmoji component is not aligned

Apparently, something went wrong during merge. It should look like this:
Bildschirmfoto 2023-05-07 um 09 06 21

**Comment by xKRISTOFx** [comment]
merged carousel update from @rvaidun; there are some bugs with it but currently no idea how to fix maybe later i have more time. @ronaldrupp if you have idea how to fix that not aligned button pleas update your fork from my  and pr solution

**Comment by ronaldrupp** [comment]
@xKRISTOFx PR:
https://github.com/xKRISTOFx/Befake_xKx/pull/25

**Comment by xKRISTOFx** [comment]
> @xKRISTOFx PR: [xKRISTOFx#25](https://github.com/xKRISTOFx/Befake_xKx/pull/25)

why U closed?

**Comment by ronaldrupp** [comment]
found some bugs.. gonna reopen when ready :)

**Comment by xKRISTOFx** [comment]
@ronaldrupp  @rvaidun  there are still two bugs in carousels 1. created when merging carousels and new css from @ronaldrupp  it looks like two posts are in first slot shrinked and second slot is empty. 2. this bug is existing since @rvaidun implemented whole thing, it is impossible to interact with photos in posts in carousels ( for example you cannot swich primary and secondnary foto) because some hitbox is overlaping, I discoverd that probable cause is container for arrows to swich slots.

**Comment by xKRISTOFx** [comment]
@ronaldrupp  you made good improvements with realmojis both posting and displaying, but because of that old problem came back -  lots of realmojis displayed under every post, and it makes using page quite uncomfy, old sollution was button by @FekyDEV but now i think it is beter to create horizontal slider just like in bereal app. What do you think @rvaidun?

**Comment by ronaldrupp** [comment]
@xKRISTOFx so same like how instagram stories are displayed?

**Comment by xKRISTOFx** [comment]
> @xKRISTOFx so same like how instagram stories are displayed?

yes, thaht's how bereal's app displays it too

**Comment by ronaldrupp** [comment]
> > @xKRISTOFx so same like how instagram stories are displayed?
> 
> yes, thaht's how bereal's app displays it too

ahh, okay. i was trying to do this too, but after the change to display every post to a carousel, the realmoji container would interfere with the post container when trying to swipe to left or to right. 

Are the two bugs on the preview link?

**Comment by rvaidun** [comment]
i'm trying to mimic the BeReal app which currently uses carousel for posts. @xKRISTOFx do you prefer carousel or having separate posts for multiple BeReals. Also takes up less space on the page. @xKRISTOFx  i like the idea of making realmojis horizontally scrolling just like the app

**Comment by rvaidun** [comment]
Thanks for pointing out the bug with the carousel. it's impossible to leave comments too.

**Comment by xKRISTOFx** [comment]
I think both layouts are cool. The carousel captures the feel of the bereal and the app, reduces scrolling, and allows you to see a person's bereal right away. The separate posts layout requires more scrolling, but is more user friendly (you make one move), and also has the advantage of allowing you to see which bereals were when in relation to each other, like a vertical timeline. I'm not able to choose a favorite, maybe it's worth making a poll for users or implementing the possibility to choose in the prefered layout. Or make an additional timeline.

**Comment by xKRISTOFx** [comment]
> > > @xKRISTOFx so same like how instagram stories are displayed?
> > 
> > 
> > yes, thaht's how bereal's app displays it too
> 
> ahh, okay. i was trying to do this too, but after the change to display posts in a carousel, the realmoji container would interfere with the carousel container when trying to swipe to left or to right.
> 
> In my opinion posts shouldn't be in a carousel. scrolling down is much better in my opinion. realmojis can then be in a horizontal, scrollable container.
> 
> Are the two bugs on the preview link?

on npm run dev, but on preview should be the same

**Comment by ronaldrupp** [comment]
> i'm trying to mimic the BeReal app which currently uses carousel for posts. @xKRISTOFx do you prefer carousel or having separate posts for multiple BeReals. Also takes up less space on the page. @xKRISTOFx i like the idea of making realmojis horizontally scrolling just like the app

ahh okay, got it.. Do you guys use some sort of test accounts or do you use your real private ones?

**Comment by xKRISTOFx** [comment]
I use private acc only

**Comment by xKRISTOFx** [comment]
Integrated newest fixes from dev branch but still carousel is bugged in this branch, the funniest looking one is for 3 bereals ;]

**Comment by ronaldrupp** [comment]
> Integrated newest fixes from dev branch but still carousel is bugged in this branch, the funniest looking one is for 3 bereals ;]

can you take a screenshot?

**Comment by xKRISTOFx** [comment]
@rvaidun nice upgrade for carousel now it is debugged.

**Comment by rvaidun** [comment]
there is a bug in the upload realmoji. On posts with a carousel the add button does not register the event

**Comment by xKRISTOFx** [comment]
> there is a bug in the upload realmoji. On posts with a carousel the add button does not register the event
 yep, and whole realmoji thing is currently broken

**Comment by xKRISTOFx** [comment]
@rvaidun popup for deletion is not integrated from there into main

**Pull request closed without merging**
