### PR TITLE
Add auto verify code when filling out

### PR DESCRIPTION
**Pull request by ronaldrupp**
### Added
- auto verifying code when filling out

### CODE REVIEW

**Comment by xKRISTOFx** [comment]
can be annoying if you make a mistake, but good overall

**Comment by ronaldrupp** [comment]
> can be annoying if you make a mistake, but good overall

Helps a lot when using the iOS sms code suggestion and normally this PR should be deployed but the config might have an error. See [PR](https://github.com/rvaidun/befake/pull/110) :)

**Comment by xKRISTOFx** [comment]
> > can be annoying if you make a mistake, but good overall
> 
> Helps a lot when using the iOS sms code suggestion and normally this PR should be deployed but the config might have an error. See [PR](https://github.com/rvaidun/befake/pull/110) :)

I know @rvaidun found it difficult at some point. That PR should be consolidated as soon as possible.

**Comment by ronaldrupp** [comment]
Closing PR. Changes are included in other [PR](https://github.com/rvaidun/befake/pull/84)

**Pull request closed without merging**
