### PR TITLE
Dev xkx - My minor corrections

### PR DESCRIPTION
**Pull request by xKRISTOFx**
integrated adding a profile picture, improved display of error messages, above the Kofi button (before they were overlapping), added support for enter_pressed events to operate with a keyboard, improved icons/replaced to vector files, which weigh less, are more customizable and deliver better quality. Minor style corrections in CSS. What's more, the country selection system has been rebuilt to be more intuitive and user-friendly, which means sorting is by country name. Flags are also displayed. Please check if everything works for you too and if you have any comments, please write them asap.

### CODE REVIEW

**Comment by xKRISTOFx** [comment]
posting profile pic is still broken i tried to use realmoji code to do it and i failed unfortunately thats why pulling into dev

**Comment by rvaidun** [comment]
Is it possible to select a default country with this new country code picker? If possible update country code select to default to the country code the device is located in, not sure how to do this.
Had to change the `sendCode` input to text instead of number since number breaks logging in with credentials
Everything else LGTM. Awesome work!

**Comment by rvaidun** [comment]
Not sure if this profile picture code works at all, I've never tested it just blindly accepted the changes 😅.
Don't know why the `uploadProfilePicture` component has a `postRealmoji` function. Component needs to be rewritten before deploying. Could just remove uploadProfilePicture feature for now

**Comment by rvaidun** [comment]
Not sure why deploy to firebase hosting on pull request job was skipped. 🥲

**Comment by xKRISTOFx** [comment]
> Not sure if this profile picture code works at all, I've never tested it just blindly accepted the changes 😅. Don't know why the `uploadProfilePicture` component has a `postRealmoji` function. Component needs to be rewritten before deploying. Could just remove uploadProfilePicture feature for now

I've tried to handle changing profilepic using that function with changed address in request, I've placed there address from previous function and it failed. I have no idea how to backswords engineer app to get working link. I think it should be removed  before deployment on main but maybe in dev  it could stay. that's why pulling into dev branch

**Comment by xKRISTOFx** [comment]
> Is it possible to select a default country with this new country code picker? If possible update country code select to default to the country code the device is located in, not sure how to do this. Had to change the `sendCode` input to text instead of number since number breaks logging in with credentials Everything else LGTM. Awesome work!

done but sometimes api doesn't respond because of too many requests from one ip but as soon as our app is making request from client side it should be fine

**Comment by rvaidun** [comment]
Didnt want to rely on APIs so I am attempting to save previously selected country code to localstorage. Works alright but when page is refreshed placeholder text shows instead of country but weirdly enough country flag stays. wasnt able to figure out how to fix it

**Comment by xKRISTOFx** [comment]
> Didnt want to rely on APIs so I am attempting to save previously selected country code to localstorage. Works alright but when page is refreshed placeholder text shows instead of country but weirdly enough country flag stays. wasnt able to figure out how to fix it

fixed and also fixed few other things

**Comment by xKRISTOFx** [comment]
> Didnt want to rely on APIs so I am attempting to save previously selected country code to localstorage. Works alright but when page is refreshed placeholder text shows instead of country but weirdly enough country flag stays. wasnt able to figure out how to fix it

bug was caused beacuse lack of updating value of this variable `this.selectedCountry = this.countries[index];`

**Comment by xKRISTOFx** [comment]
now code is saving whole object into localstorage - cookie i think it isn't problem but it could be done by saving index only

**Comment by rvaidun** [comment]
using isocode instead of dialcode since some countries have same isoCode ie USA and Canada

**Pull request merged**
