### PR TITLE
fix cors server not running

### PR DESCRIPTION
**Pull request by ggs3rvic3s**
Run ```npm run local``` to fix cors server not launching

### CODE REVIEW

**Review by xKRISTOFx — CHANGES_REQUESTED** [review]
add endline in the end of server.js file

**Comment by rvaidun** [comment]
Why do it this way instead of using concurrently?

**Comment by ggs3rvic3s** [comment]
idont know, if i press str + c it will runs cors server but shutdown at the same time the vite server

**Comment by ggs3rvic3s** [comment]
It just a hot fix, for me it works only that way.

**Comment by ggs3rvic3s** [comment]
https://github.com/rvaidun/befake/assets/75442029/3a85946c-0e08-4cfe-b7fb-ab732f7a752e

**Comment by ggs3rvic3s** [comment]
with hot fix 

https://github.com/rvaidun/befake/assets/75442029/7e4fe93e-f0b4-4315-9ffd-3233f90dce96

**Comment by rvaidun** [comment]
Have you tried the `concurrently` dev script?

**Comment by ggs3rvic3s** [comment]
Yes i tried the newest src code

**Comment by ggs3rvic3s** [comment]
but doesnt work, idk why. it was a mystery to me myself lol

**Comment by rvaidun** [comment]
The videos you sent are not showing the latest source code.

**Comment by ggs3rvic3s** [comment]
oh thx, my fault

**Pull request closed without merging**
